### ISSUE TITLE
Different count of hotels on WT explorer and debugger

### ISSUE THREAD

**Issue by czervenka** [windingtree/wt-index-debugger#3]
I can see 4 hotels in [debugger](https://index-debugger.windingtree.com/) on playground but more than 10 hotels in [explorer](https://hotel-explorer-playground.windingtree.com/).

Furthermore, clicking on hotel "read api" green label leads to 404 page.

**Comment by JirkaChadima** [comment]
Because explorer and Read API are connected to the old Index. You are looking on the new index in the debugger.

**Comment by kvbik** [comment]
it would be actually nice to easily spot it. i stumbled on that as well :)) i can imagine displaying the info in the explorer somewhere (so i don't have to go to [1] and hope it is the one). i like having the history of indexes in debugger!

[1] https://github.com/windingtree/wiki/blob/master/deployments.md

**Comment by JirkaChadima** [comment]
I've removed the lnks to read-api when it's unrelated to the shown index
