### ISSUE TITLE
Search for items by address

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-index-debugger#4]
If there's a lot of records in an index, the interface gets crowded. It would be nice to be able to search for an item by it's blockchain address.

**Comment by czervenka** [comment]
+1 It would be really helpful.

It would be also great to have a fixed url for hotel in debugger for sharing (e.g. `/<wt_index_address>/<hotel_address>

**Comment by JirkaChadima** [comment]
I'm going to close this for now. We don't have the permalink, but we can add it later if needed.

**Comment by ondrejchmelar** [comment]
We do but it's not documented, I'll add it to readme
